CREATE TABLE testuser.table1 (
  column1 VARCHAR2(20 BYTE) NOT NULL,
  column2 VARCHAR2(20 BYTE),
  CONSTRAINT table1_pk PRIMARY KEY (column1) USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING,
  CONSTRAINT table1_uk1 UNIQUE (column2) USING INDEX NOCOMPRESS
    PCTFREE 10 INITRANS 2 LOGGING
) NOCOMPRESS
PCTFREE 10 INITRANS 1 LOGGING;